F5 related updates

diff --git a/scripts/config-f5 b/scripts/config-f5
--- a/scripts/config-f5
+++ b/scripts/config-f5
@@ -15,13 +15,19 @@ if ! which jinja2 > /dev/null; then
 	exit 1
 fi
 
+if ! which vesctl > /dev/null; then
+	echo "Please install vesctl!"
+	exit 1
+fi
+
+
 TMP=/tmp/.tmp.$$
 rm -rf $TMP && mkdir $TMP
 OUT=/tmp/out
 rm -rf $OUT && mkdir $OUT
 
-mv cleanup.sh cleanup.sh.bak
-echo "f5/bin/remove_registrations.sh" >> cleanup.sh
+mv f5/cleanup.sh f5/cleanup.sh.bak
+echo "f5/bin/remove_registrations.sh" >> f5/cleanup.sh
 
 wait_pod_exists()
 {
@@ -76,13 +82,13 @@ for site in $SITE_LIST
 do
 	CONTEXT=$(getContext $site) || exit 1
 
-	echo $CONTEXT: Launching F5 Ingress 
+	echo $CONTEXT: Launching F5 Ingress ...
 
 	# Create the F5 Ingress (VES) in OpenShift
 	cat $HCD_CONF | yq ".sites.$site" | jinja2 yaml/f5/site.yaml -Dsite=$site -Dtoken=$TOKEN > $OUT/site-$site.yaml
 	oc --context=$CONTEXT create -f $OUT/site-$site.yaml -n ves-system
 
-	echo "oc --context=$CONTEXT delete -f $OUT/site-$site.yaml" >> cleanup.sh 
+	echo "oc --context=$CONTEXT delete -f $OUT/site-$site.yaml" >> f5/cleanup.sh 
 done
 
 
@@ -106,7 +112,6 @@ echo "Please confirm pending registrations by clicking on the blue tick in the F
 echo "Home -> Multi-Cloud Network Connect -> Manage -> Site Management -> Registrations"
 echo "https://f5-asean.console.ves.volterra.io/web/workspaces/multi-cloud-network-connect/manage/site_management/registrations;tab=pending"
 echo "About 2 to 3 mins after confirmation, the ver-0 pod will start."
-echo 
 
 # Wait for F5 Ingress to come up ...
 
@@ -114,11 +119,11 @@ for site in $SITE_LIST
 do
 	export CONTEXT=$(getContext $site) || exit 1
 
-	## echo -n "$CONTEXT: Waiting for the ver-0 pod to start in ves-system namespace on cluster $CONTEXT ... "
+	## echo -n "$CONTEXT: Waiting for the ver-0 pod to start in ves-system namespace on context $CONTEXT ... "
 	wait_pod_exists ver-0 -n ves-system
-	echo done
+	#echo done
 
-	echo -n "$CONTEXT: Waiting for all pods to be ready in ves-system namespace on cluster $CONTEXT ... "
+	echo -n "$CONTEXT: Waiting for all pods to be ready in ves-system namespace on context $CONTEXT ... "
 	#CONTEXT=$(getContext $site) wait_all_pods_ready -n ves-system 
 	wait_all_pods_ready -n ves-system 
 	echo done
@@ -146,13 +151,13 @@ done
 
 
 ########################################
-# Now, create the http loadbalancers ...
+# Now, create the http load balancers ...
 ########################################
 
 echo Creating basic health check config ...
 vesctl configuration create healthcheck -i yaml/f5/health.yaml || \
 	vesctl configuration replace healthcheck -i yaml/f5/health.yaml || exit 1
-echo "vesctl configuration delete healthcheck basic-healthcheck -n multi-cloud-openshift" >> cleanup.sh
+echo "vesctl configuration delete healthcheck basic-healthcheck -n multi-cloud-openshift" >> f5/cleanup.sh
 
 
 INGRESS_LIST=$(cat $HCD_CONF  | yq '.ingresses[] | key')
@@ -160,33 +165,41 @@ INGRESS_LIST=$(cat $HCD_CONF  | yq '.ingresses[] | key')
 # Create the Origin Pools, one for each ingress
 for ingress in $INGRESS_LIST
 do
-	echo Creating Origin Pool [op-$ingress] ...
+	op_name=op-$ingress-$BASE_DOMAIN_READABLE
+	conffile=$OUT/$op_name.yaml
 
-	cat $HCD_CONF | jinja2 yaml/f5/op.yaml -Dingress=$ingress > $OUT/op-$ingress.yaml || exit 1
+	echo Creating Origin Pool [$op_name] ...
 
-	vesctl configuration create origin_pool -i $OUT/op-$ingress.yaml || \
-		vesctl configuration replace origin_pool -i $OUT/op-$ingress.yaml || exit 1
+	cat $HCD_CONF | jinja2 yaml/f5/op.yaml -Dingress=$ingress -Ddomain_readable=$BASE_DOMAIN_READABLE > $conffile || exit 1
 
-	echo "vesctl configuration delete origin_pool op-$ingress -n multi-cloud-openshift" >> cleanup.sh
+	vesctl configuration create origin_pool -i $conffile || \
+		vesctl configuration replace origin_pool -i $conffile || exit 1
+
+	echo "vesctl configuration delete origin_pool $op_name -n multi-cloud-openshift" >> f5/cleanup.sh
 done
 
 # Create the http load balancers, one for each ingress 
 for ingress in $INGRESS_LIST
 do
-	echo Creating HTTP Load Balancer [lb-$ingress-$BASE_DOMAIN_READABLE] ...
+	lb_name=lb-$ingress-$BASE_DOMAIN_READABLE
+	conffile=$OUT/$lb_name.yaml
 
-	cat $HCD_CONF | yq ".ingresses.$ingress" | jinja2 yaml/f5/lb.yaml -Dingress=$ingress -Ddomain=$BASE_DOMAIN -Ddomain_readable=$BASE_DOMAIN_READABLE > $OUT/lb-$ingress.yaml
+	echo Creating HTTP Load Balancer [$lb_name] ...
 
-	vesctl configuration create http_loadbalancer -i $OUT/lb-$ingress.yaml || \
-		vesctl configuration replace http_loadbalancer -i $OUT/lb-$ingress.yaml || exit 1
-	echo "vesctl configuration delete http_loadbalancer lb-$ingress-$BASE_DOMAIN_READABLE -n multi-cloud-openshift" >> cleanup.sh
+	cat $HCD_CONF | yq ".ingresses.$ingress" | jinja2 yaml/f5/lb.yaml -Dingress=$ingress -Ddomain=$BASE_DOMAIN -Ddomain_readable=$BASE_DOMAIN_READABLE > $conffile
+
+	vesctl configuration create http_loadbalancer -i $conffile || \
+		vesctl configuration replace http_loadbalancer -i $conffile || exit 1
+	echo "vesctl configuration delete http_loadbalancer $lb_name -n multi-cloud-openshift" >> f5/cleanup.sh
 done
 
 echo All done
 
-echo 'set -x' >> cleanup.sh
+echo All applied F5 configurations can be found in the $OUT directory for reference. 
+echo
+echo 'set -x' >> f5/cleanup.sh
 echo 
 echo To clean up configurations, run one of the following commands:
-echo "tail -r cleanup.sh | bash                         # to cleanup the f5 ingress and all f5 configurations"
-echo "grep -v \"oc \" cleanup.sh | tail -r | bash         # to cleanup all f5 configurations only"
+echo "tail -r f5/cleanup.sh | bash                         # to cleanup the f5 ingress and all f5 configurations"
+echo "grep -v \"oc \" f5/cleanup.sh | tail -r | bash         # to cleanup all f5 configurations only"
 
