Use separate kubeconfig files instead of calling oc login

diff --git a/scripts/delete-hugepages b/scripts/delete-hugepages
--- a/scripts/delete-hugepages
+++ b/scripts/delete-hugepages
@@ -1,94 +1,48 @@
 #!/bin/bash
 
-TMP_KUBECONFIG=/tmp/kubeconfig
-
-CLUSTERS="coolstore-a coolstore-b coolstore-c"
-CONFIG=""
+TMPDIR=/tmp/deletehugepages
 
 cd `dirname $0`
 BASE=`pwd`
 cd - >> /dev/null
 
-for cluster in $CLUSTERS; do
-  secret="$(oc get -n openshift-gitops secret/${cluster}-cluster-secret -o jsonpath='{.data}')"
-  token="$(echo -n $secret | jq -r '.config' | base64 -d | jq -r '.bearerToken')"
-  apiserver="$(echo -n $secret | jq -r '.server' | base64 -d)"
+source ${BASE}/../config.sh
 
-  if [ -z "$token" ]; then
-    echo "could not extract token for $cluster"
+# setup kubeconfig files for each cluster
+rm -rf $TMPDIR
+mkdir -p $TMPDIR
+for clustername in ${CLUSTER_NAMES[@]}; do
+  config="$(oc get -n $clustername secrets -l hive.openshift.io/secret-type=kubeconfig -o jsonpath='{.items[0].data.kubeconfig}' 2>/dev/null)"
+  if [ -z "$config" ]; then
+    echo "could not retrieve kubeconfig for $clustername"
     exit 1
   fi
-
-  if [ -z "$apiserver" ]; then
-    echo "could not extract API server for $cluster"
-    exit 1
-  fi
-
-  CONFIG="$CONFIG $cluster $token $apiserver"
+  echo -n "$config" | base64 -d > ${TMPDIR}/${clustername}
 done
 
-function login {
-  local token="$1"
-  local api="$2"
 
-  export KUBECONFIG=$TMP_KUBECONFIG
-  rm -f $KUBECONFIG
-  touch $KUBECONFIG
+# unlabel nodes
+for clustername in ${CLUSTER_NAMES[@]}; do
+  cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
+  echo "removing labels from nodes in ${clustername}..."
+  for w in $($cmd get node -oname -l node-role.kubernetes.io/worker=); do
+    # Exclude any submariner gateway nodes
+    $cmd get $w --show-labels | grep -q submariner.io/gateway=true && continue
 
-  echo "logging in to $api"
-  oc login $api --token=$token --insecure-skip-tls-verify
-}
-
-function login_and_unlabel_nodes {
-  local clustername
-  local token
-  local apiserver
-
-  while [ $# -gt 0 ]; do
-    clustername="$1"
-    token="$2"
-    apiserver="$3"
-    shift
-    shift
-    shift
-    echo "$clustername $apiserver"
-    login $token $apiserver
-
-    for w in `oc get node -oname -l node-role.kubernetes.io/worker=`; do
-      # Exclude any submariner gateway nodes
-      oc get $w --show-labels | grep -q submariner.io/gateway=true && continue
-
-      oc label $w node-role.kubernetes.io/worker-hp-
-    done
+    $cmd label $w node-role.kubernetes.io/worker-hp-
   done
-}
+done
 
-function login_and_wait_for_mcp {
-  local clustername
-  local token
-  local apiserver
 
-  while [ $# -gt 0 ]; do
-    clustername="$1"
-    token="$2"
-    apiserver="$3"
-    shift
-    shift
-    shift
-    echo "$clustername $apiserver"
-    login $token $apiserver
-
-    echo -n "waiting for worker-hp MCP on $clustername to be ready..."
-	while ! oc get mcp worker-hp -o jsonpath="{.status.conditions[?(@.type=='Updating')].status}" | grep False > /dev/null; do
-	  echo -n "."
-	  sleep 30
-	done
-	echo "done"
-
+# wait for mcp
+for clustername in ${CLUSTER_NAMES[@]}; do
+  cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
+  echo -n "waiting for worker-hp MCP on $clustername to be ready..."
+  while ! $cmd get mcp worker-hp -o jsonpath="{.status.conditions[?(@.type=='Updating')].status}" | grep False > /dev/null; do
+    echo -n "."
+    sleep 30
   done
-}
+  echo "done"
+done
 
-login_and_unlabel_nodes $CONFIG
-login_and_wait_for_mcp $CONFIG
-
-rm -f $KUBECONFIG
+rm -rf $TMPDIR
diff --git a/scripts/generate-orders b/scripts/generate-orders
--- a/scripts/generate-orders
+++ b/scripts/generate-orders
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-TMP_KUBECONFIG=/tmp/kubeconfig
+TMPDIR=/tmp/generateorders
 
 cd $(dirname $0)
 BASE=$(pwd)
@@ -8,56 +8,45 @@ cd - >> /dev/null
 
 source ${BASE}/../config.sh
 
+cmd="oc"
+
 function get_kafka() {
-  oc get -n $PROJ deploy/kafka-0 -o name 2>/dev/null
+  $cmd get -n $PROJ deploy/kafka-0 -o name 2>/dev/null
 }
 
 # check if we have everything deployed on the connected cluster (single
 # cluster install)
 KAFKA="$(get_kafka)"
+
 if [ -z "$KAFKA" ]; then
   echo "kafka is not on the connected cluster - trying to see if we can connect to coolstore-a"
 
-  CLUSTER_SECRET="$(oc get -n openshift-gitops secret/coolstore-a-cluster-secret -o jsonpath='{.data}' 2>/dev/null)"
-  if [ -z "$CLUSTER_SECRET" ]; then
-    echo "could not get coolstore-a cluster secret"
-    exit 1
-  fi
-  API="$(echo $CLUSTER_SECRET | jq -r .server | base64 -d)"
-  if [ -z "$API" ]; then
-    echo "could not get coolstore-a API server"
-    exit 1
-  fi
-  CONFIG="$(echo $CLUSTER_SECRET | jq -r .config | base64 -d)"
-  if [ -z "$CONFIG" ]; then
-    echo "could not get coolstore-a config"
-    exit 1
-  fi
-  TOKEN="$(echo $CONFIG | jq -r .bearerToken)"
-  if [ -z "$TOKEN" ]; then
-    echo "could not get coolstore-a bearer token"
-    exit 1
-  fi
-  rm -f $TMP_KUBECONFIG
-  touch $TMP_KUBECONFIG
-  export KUBECONFIG=$TMP_KUBECONFIG
-  set -e
-  echo "logging into coolstore-a..."
-  oc login --insecure-skip-tls-verify=true --token="$TOKEN" "$API"
-  set +e
+  # setup kubeconfig for coolstore-a
+  rm -rf $TMPDIR
+  mkdir -p $TMPDIR
+  for clustername in coolstore-a; do
+    config="$(oc get -n $clustername secrets -l hive.openshift.io/secret-type=kubeconfig -o jsonpath='{.items[0].data.kubeconfig}' 2>/dev/null)"
+    if [ -z "$config" ]; then
+      echo "could not retrieve kubeconfig for $clustername"
+      exit 1
+    fi
+    echo -n "$config" | base64 -d > ${TMPDIR}/${clustername}
+  done
+  cmd="$cmd --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/${clustername}"
+
   KAFKA="$(get_kafka)"
   if [ -z "$KAFKA" ]; then
     echo "kafka is not installed on coolstore-a"
-    rm -f $TMP_KUBECONFIG
+    rm -f $TMPDIR
     exit 1
   fi
 fi
 
 echo "creating order generator job"
-oc apply -n $PROJ -f ${BASE}/../yaml/order-generator/order-generator-job.yaml
+$cmd apply -n $PROJ -f ${BASE}/../yaml/order-generator/order-generator-job.yaml
 echo "sleeping"
 sleep 30
 echo "deleting order generator job"
-oc delete -n $PROJ -f ${BASE}/../yaml/order-generator/order-generator-job.yaml
+$cmd delete -n $PROJ -f ${BASE}/../yaml/order-generator/order-generator-job.yaml
 
-rm -f $TMP_KUBECONFIG
+rm -f $TMPDIR
diff --git a/scripts/modify-alert-manager-settings b/scripts/modify-alert-manager-settings
--- a/scripts/modify-alert-manager-settings
+++ b/scripts/modify-alert-manager-settings
@@ -1,32 +1,30 @@
 #!/bin/bash
 
-TMP_KUBECONFIG=/tmp/kubeconfig
+TMPDIR=/tmp/alertmanagersettings
 
-TOKEN="$(oc get -n openshift-gitops secret coolstore-a-cluster-secret -o jsonpath='{.data.config}' | base64 -d | jq -r '.bearerToken')"
-API_SERVER="$(oc get -n openshift-gitops secret coolstore-a-cluster-secret -o jsonpath='{.data.server}' | base64 -d)"
+cd `dirname $0`
+BASE=`pwd`
+cd - >> /dev/null
 
-echo "token = $TOKEN"
-echo "api = $API_SERVER"
+source ${BASE}/../config.sh
 
-if [ -z "$TOKEN" ]; then
-  echo "could not get coolstore-a token"
-  exit 1
-fi
+# setup kubeconfig files for each cluster
+rm -rf $TMPDIR
+mkdir -p $TMPDIR
+for clustername in coolstore-a; do
+  config="$(oc get -n $clustername secrets -l hive.openshift.io/secret-type=kubeconfig -o jsonpath='{.items[0].data.kubeconfig}' 2>/dev/null)"
+  if [ -z "$config" ]; then
+    echo "could not retrieve kubeconfig for $clustername"
+    exit 1
+  fi
+  echo -n "$config" | base64 -d > ${TMPDIR}/${clustername}
+done
 
-if [ -z "$API_SERVER" ]; then
-  echo "could not get coolstore-a API server"
-  exit 1
-fi
-
-export KUBECONFIG=$TMP_KUBECONFIG
-rm -f $KUBECONFIG
-touch $KUBECONFIG
-
-oc login $API_SERVER --token=$TOKEN --insecure-skip-tls-verify
+cmd="oc --insecure-skip-tls-verify --kubeconfig=${TMPDIR}/coolstore-a"
 
 set -e
 
-oc get secret/alertmanager-main \
+$cmd get secret/alertmanager-main \
   -n openshift-monitoring \
   -o jsonpath='{.data.alertmanager\.yaml}' \
 | \
@@ -37,10 +35,10 @@ sed \
   -e 's/"group_wait".*/"group_wait": "15s"/' \
 > /tmp/alertmanager.yaml
 
-oc set data secret/alertmanager-main \
+$cmd set data secret/alertmanager-main \
   -n openshift-monitoring \
   --from-file=alertmanager.yaml=/tmp/alertmanager.yaml
 
 rm -f /tmp/alertmanager.yaml
 
-rm -f $KUBECONFIG
+rm -rf $TMPDIR
