Setup console banner for coolstore-c

diff --git a/scripts/setup-console-banners b/scripts/setup-console-banners
--- a/scripts/setup-console-banners
+++ b/scripts/setup-console-banners
@@ -2,35 +2,27 @@
 
 TMP_KUBECONFIG=/tmp/kubeconfig
 
-TOKEN_A="$(oc get -n openshift-gitops secret coolstore-a-cluster-secret -o jsonpath='{.data.config}' | base64 -d | jq -r '.bearerToken')"
-API_SERVER_A="$(oc get -n openshift-gitops secret coolstore-a-cluster-secret -o jsonpath='{.data.server}' | base64 -d)"
-TOKEN_B="$(oc get -n openshift-gitops secret coolstore-b-cluster-secret -o jsonpath='{.data.config}' | base64 -d | jq -r '.bearerToken')"
-API_SERVER_B="$(oc get -n openshift-gitops secret coolstore-b-cluster-secret -o jsonpath='{.data.server}' | base64 -d)"
+CLUSTERS="coolstore-a coolstore-b coolstore-c"
 
-echo "coolstore-a token = $TOKEN_A"
-echo "coolstore-a api = $API_SERVER_A"
-echo "coolstore-b token = $TOKEN_B"
-echo "coolstore-b api = $API_SERVER_B"
+CONFIG=""
 
-if [ -z "$TOKEN_A" ]; then
-  echo "could not get coolstore-a token"
-  exit 1
-fi
+for cluster in $CLUSTERS; do
+  secret="$(oc get -n openshift-gitops secret/${cluster}-cluster-secret -o jsonpath='{.data}')"
+  token="$(echo -n $secret | jq -r '.config' | base64 -d | jq -r '.bearerToken')"
+  apiserver="$(echo -n $secret | jq -r '.server' | base64 -d)"
 
-if [ -z "$API_SERVER_A" ]; then
-  echo "could not get coolstore-a API server"
-  exit 1
-fi
+  if [ -z "$token" ]; then
+    echo "could not extract token for $cluster"
+    exit 1
+  fi
 
-if [ -z "$TOKEN_B" ]; then
-  echo "could not get coolstore-b token"
-  exit 1
-fi
+  if [ -z "$apiserver" ]; then
+    echo "could not extract API server for $cluster"
+    exit 1
+  fi
 
-if [ -z "$API_SERVER_B" ]; then
-  echo "could not get coolstore-b API server"
-  exit 1
-fi
+  CONFIG="$CONFIG $cluster $token $apiserver"
+done
 
 function login {
   local token="$1"
@@ -58,14 +50,28 @@ spec:
 EOF
 }
 
+function login_and_apply_banner {
+  local clustername
+  local token
+  local apiserver
+
+  while [ $# -gt 0 ]; do
+    clustername="$1"
+    token="$2"
+    apiserver="$3"
+    shift
+    shift
+    shift
+    echo "$clustername $apiserver"
+    login $token $apiserver
+    apply_banner $clustername
+  done
+}
+
 set -e
 
 apply_banner "Hub Cluster"
 
-login $TOKEN_A $API_SERVER_A
-apply_banner "coolstore-a"
-
-login $TOKEN_B $API_SERVER_B
-apply_banner "coolstore-b"
+login_and_apply_banner $CONFIG
 
 rm -f $KUBECONFIG
